apiVersion: v1
kind: Service
metadata:
  name: linkedin-loadbalancer
  namespace: linkedin
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: profile-api
  ports:
  - name: profile
    port: 8001
    targetPort: 8001
  - name: jobs
    port: 8002
    targetPort: 8002
  - name: applications
    port: 8003
    targetPort: 8003
  - name: messaging
    port: 8004
    targetPort: 8004
  - name: analytics
    port: 8005
    targetPort: 8005
  - name: ai
    port: 8006
    targetPort: 8006
