apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init
  namespace: linkedin
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS linkedin_db;
    CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'apppassword';
    GRANT ALL PRIVILEGES ON linkedin_db.* TO 'appuser'@'%';
    FLUSH PRIVILEGES;
