apiVersion: v1
kind: Secret
metadata:
  name: linkedin-secrets
  namespace: linkedin
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: rootpassword
  MYSQL_PASSWORD: apppassword
  MONGO_ROOT_PASSWORD: rootpassword
  REDIS_PASSWORD: redispassword
  OPENAI_API_KEY: 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
