version: '3.8'
services:
  job-api:
    environment:
      REDIS_ENABLED: "true"
      KAFKA_ENABLED: "true"
  application-api:
    environment:
      ENABLE_KAFKA: "true"
  analytics-worker:
    environment:
      KAFKA_BROKER: kafka:9092
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
